repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
  - repo: local
    hooks:
      - id: generate-workflows
        name: Generate Terraform Workflows
        entry: ./scripts/generate-workflows.sh
        language: system
        files: ^environments/
        pass_filenames: false