name: _Discord Notification

on:
  workflow_call:
    inputs:
      status:
        description: 'Workflow status (success/failure)'
        required: true
        type: string
      workflow-name:
        description: 'Workflow name'
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}:role/GitHubActions-MultiRepo
          aws-region: us-east-2

      - name: Get Discord webhook URL
        id: webhook
        run: |
          WEBHOOK_URL=""
          echo "Repository: ${{ github.event.repository.name }}"
          
          # Try to get the webhook directly
          WEBHOOKS=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-2:025066240222:secret:all/heezy/discord/webhooks-V7JnBe --query SecretString --output text 2>/dev/null)
          if [ $? -eq 0 ] && [ -n "$WEBHOOKS" ]; then
            echo "Webhooks retrieved successfully"
            WEBHOOK_URL=$(echo "$WEBHOOKS" | jq -r '."${{ github.event.repository.name }}" // ""' 2>/dev/null || echo "")
          else
            echo "Failed to retrieve webhook secret"
          fi
          
          echo "Final webhook URL: $WEBHOOK_URL"
          echo "url=$WEBHOOK_URL" >> $GITHUB_OUTPUT

      - name: Send Discord notification
        if: steps.webhook.outputs.url != ''
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ steps.webhook.outputs.url }}
        with:
          args: |
            ${{ inputs.status == 'success' && '✅' || '❌' }} **${{ github.event.repository.name }}** - ${{ inputs.workflow-name }} - ${{ github.ref_name }} - ${{ inputs.status == 'success' && 'PASSED' || 'FAILED' }}
            
            **Workflow:** ${{ github.workflow }}
            **Run:** ${{ github.run_number }}
            **Commit:** `${{ github.sha }}`
            **Author:** ${{ github.actor }}
            [View Run](<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>)
