name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: terraform-workflow-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      production-heezy: ${{ steps.changes.outputs.production-heezy }}
      production-aws: ${{ steps.changes.outputs.production-aws }}
      dev-heezy: ${{ steps.changes.outputs.dev-heezy }}
      dev-aws: ${{ steps.changes.outputs.dev-aws }}
      shared: ${{ steps.changes.outputs.shared }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            production-heezy:
              - 'environments/production/heezy/**'
            production-aws:
              - 'environments/production/aws/**'
            dev-heezy:
              - 'environments/dev/heezy/**'
            dev-aws:
              - 'environments/dev/aws/**'
            shared:
              - 'shared/**'

  get-runner-credentials:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      runner-access-key: ${{ steps.get-creds.outputs.access-key }}
      runner-secret-key: ${{ steps.get-creds.outputs.secret-key }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}:role/GitHubActions-MultiRepo
          aws-region: us-east-2

      - name: Get runner credentials from AWS Secrets
        id: get-creds
        run: |
          CREDS=$(aws secretsmanager get-secret-value --secret-id production/heezy/github_runner/aws_credentials --query SecretString --output text)
          echo "access-key=$(echo $CREDS | jq -r '.AWS_ACCESS_KEY_ID')" >> $GITHUB_OUTPUT
          echo "secret-key=$(echo $CREDS | jq -r '.AWS_SECRET_ACCESS_KEY')" >> $GITHUB_OUTPUT

  terraform-plan:
    needs: [detect-changes, get-runner-credentials]
    runs-on: self-hosted
    timeout-minutes: 180
    strategy:
      max-parallel: 4
      matrix:
        workspace:
          - { env: "production", component: "heezy", path: "environments/production/heezy" }
          - { env: "production", component: "aws", path: "environments/production/aws" }
          - { env: "dev", component: "heezy", path: "environments/dev/heezy" }
          - { env: "dev", component: "aws", path: "environments/dev/aws" }
    steps:
      - name: Check if workspace should run
        id: should-run
        run: |
          case "${{ matrix.workspace.env }}-${{ matrix.workspace.component }}" in
            "production-heezy")
              echo "run=${{ needs.detect-changes.outputs.production-heezy == 'true' || needs.detect-changes.outputs.shared == 'true' }}" >> $GITHUB_OUTPUT
              ;;
            "production-aws")
              echo "run=${{ needs.detect-changes.outputs.production-aws == 'true' }}" >> $GITHUB_OUTPUT
              ;;
            "dev-heezy")
              echo "run=${{ needs.detect-changes.outputs.dev-heezy == 'true' || needs.detect-changes.outputs.shared == 'true' }}" >> $GITHUB_OUTPUT
              ;;
            "dev-aws")
              echo "run=${{ needs.detect-changes.outputs.dev-aws == 'true' }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Checkout
        if: steps.should-run.outputs.run == 'true'
        uses: actions/checkout@v4

      - name: Terraform Init and Plan
        if: steps.should-run.outputs.run == 'true'
        working-directory: ${{ matrix.workspace.path }}
        run: |
          TERRAFORM_CREDS=$(AWS_ACCESS_KEY_ID=${{ needs.get-runner-credentials.outputs.runner-access-key }} \
          AWS_SECRET_ACCESS_KEY=${{ needs.get-runner-credentials.outputs.runner-secret-key }} \
          AWS_DEFAULT_REGION=us-east-2 \
          aws sts assume-role --role-arn arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}:role/productionATerraformStateBackend --role-session-name terraform-session)
          
          AWS_ACCESS_KEY_ID=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.AccessKeyId') \
          AWS_SECRET_ACCESS_KEY=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SecretAccessKey') \
          AWS_SESSION_TOKEN=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SessionToken') \
          terraform init
          
          AWS_ACCESS_KEY_ID=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.AccessKeyId') \
          AWS_SECRET_ACCESS_KEY=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SecretAccessKey') \
          AWS_SESSION_TOKEN=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SessionToken') \
          terraform plan -no-color -out=tfplan
          
          AWS_ACCESS_KEY_ID=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.AccessKeyId') \
          AWS_SECRET_ACCESS_KEY=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SecretAccessKey') \
          AWS_SESSION_TOKEN=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SessionToken') \
          terraform show -no-color tfplan > plan.txt

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request' && steps.should-run.outputs.run == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('${{ matrix.workspace.path }}/plan.txt', 'utf8');
            const body = `## Terraform Plan - ${{ matrix.workspace.env }}/${{ matrix.workspace.component }}
            \`\`\`
            ${plan}
            \`\`\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

  terraform-apply:
    if: github.ref == 'refs/heads/main'
    needs: [detect-changes, get-runner-credentials, terraform-plan]
    runs-on: self-hosted
    timeout-minutes: 180
    environment: production
    concurrency:
      group: terraform-deploy-${{ matrix.workspace.env }}-${{ matrix.workspace.component }}
      cancel-in-progress: false
    strategy:
      max-parallel: 4
      matrix:
        workspace:
          - { env: "production", component: "heezy", path: "environments/production/heezy" }
          - { env: "production", component: "aws", path: "environments/production/aws" }
          - { env: "dev", component: "heezy", path: "environments/dev/heezy" }
          - { env: "dev", component: "aws", path: "environments/dev/aws" }
    steps:
      - name: Check if workspace should run
        id: should-run
        run: |
          case "${{ matrix.workspace.env }}-${{ matrix.workspace.component }}" in
            "production-heezy")
              echo "run=${{ needs.detect-changes.outputs.production-heezy == 'true' || needs.detect-changes.outputs.shared == 'true' }}" >> $GITHUB_OUTPUT
              ;;
            "production-aws")
              echo "run=${{ needs.detect-changes.outputs.production-aws == 'true' }}" >> $GITHUB_OUTPUT
              ;;
            "dev-heezy")
              echo "run=${{ needs.detect-changes.outputs.dev-heezy == 'true' || needs.detect-changes.outputs.shared == 'true' }}" >> $GITHUB_OUTPUT
              ;;
            "dev-aws")
              echo "run=${{ needs.detect-changes.outputs.dev-aws == 'true' }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Checkout
        if: steps.should-run.outputs.run == 'true'
        uses: actions/checkout@v4

      - name: Terraform Init and Apply
        if: steps.should-run.outputs.run == 'true'
        working-directory: ${{ matrix.workspace.path }}
        run: |
          TERRAFORM_CREDS=$(AWS_ACCESS_KEY_ID=${{ needs.get-runner-credentials.outputs.runner-access-key }} \
          AWS_SECRET_ACCESS_KEY=${{ needs.get-runner-credentials.outputs.runner-secret-key }} \
          AWS_DEFAULT_REGION=us-east-2 \
          aws sts assume-role --role-arn arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}:role/productionATerraformStateBackend --role-session-name terraform-session)
          
          AWS_ACCESS_KEY_ID=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.AccessKeyId') \
          AWS_SECRET_ACCESS_KEY=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SecretAccessKey') \
          AWS_SESSION_TOKEN=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SessionToken') \
          terraform init
          
          AWS_ACCESS_KEY_ID=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.AccessKeyId') \
          AWS_SECRET_ACCESS_KEY=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SecretAccessKey') \
          AWS_SESSION_TOKEN=$(echo $TERRAFORM_CREDS | jq -r '.Credentials.SessionToken') \
          terraform apply -auto-approve

  notify:
    if: always()
    needs: [terraform-apply]
    uses: ./.github/workflows/_discord-notify.yml
    with:
      status: ${{ (needs.terraform-apply.result == 'success' || needs.terraform-apply.result == 'skipped') && 'success' || 'failure' }}
      workflow-name: 'Terraform Deploy'
    secrets: inherit
